### ISSUE TITLE
Add coverage for the URLs under "Other Applications," to catch bug 1119968

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#739]
Neither http://selenium.qa.mtv2.mozilla.com:8080/job/amo.dev.mobile.saucelabs/ nor http://selenium.qa.mtv2.mozilla.com:8080/view/AMO/job/amo.dev.saucelabs/ caught https://bugzilla.mozilla.org/show_bug.cgi?id=1119968

Let's get basic coverage of the static URLs under "Other Applications," in the header nav.

**Comment by stephendonner** [comment]
@AndreiH or @bobsilverberg can either/both of you take a look/patch/review/merge? :-)  Thanks!

**Comment by AndreiH** [comment]
On it! :)

**Comment by AndreiH** [comment]
I didn't find this option on Mobile thought, so I added coverage for Desktop

**Comment by viorelaioia** [comment]
PR was merged.
