### ISSUE TITLE
Investigate and fix test_that_complete_themes_can_be_sorted_by_popularity 

### ISSUE THREAD

**Issue by AndreiH** [mozilla/Addon-Tests#741]
This started to fail quite often on dev

http://selenium.qa.mtv2.mozilla.com:8080/view/AMO/job/amo.dev/1817/testReport/junit/tests.desktop.test_complete_themes/TestCompleteThemes/test_that_complete_themes_can_be_sorted_by_popularity/

**Comment by AndreiH** [comment]
This is failing very strangely and only on AMO.dev in-house.
I investigated this and I cannot find the cause of this failure for now. Also could not reproduce this locally.
Assert is failing with message : "AssertionError: 272 is not before 2456"

See HTML report: http://selenium.qa.mtv2.mozilla.com:8080/view/AMO/job/amo.dev/1823/HTML_Report/

**Comment by m8ttyB** [comment]
Looking at the screenshot I don't immediately understand why the test is comparing the value of the download rate for the last item on the page [the lowest download rate - `272`] against the first theme [highest download rate - `2456`].

Let the dig begin :)

![screenshot](https://cloud.githubusercontent.com/assets/63193/6377506/b50a250a-bce1-11e4-85aa-4e7ef50d9b61.png)

**Comment by davehunt** [comment]
> Looking at the screenshot I don't immediately understand why the test is comparing the value of the download rate for the last item on the page [the lowest download rate - 272] against the first theme [highest download rate - 2456].

This is because the test is checking that we can sort by download rate. I'm going to close this as it hasn't had any activity since February, and we've since rewritten the assert. If this fails again we should at least have more information in the trace.
