### ISSUE TITLE
On prod, test_that_carousel_works fails, and should probably use --apibaseurl, rather than --baseurl

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#745]
xref: https://bugzilla.mozilla.org/show_bug.cgi?id=1128975
![screenshot from 2015-02-03 17_28_35](https://cloud.githubusercontent.com/assets/387249/6197106/2b0b593c-b395-11e4-9bb5-cd036d47399d.png)

In the Discovery Pane tests on prod, we just make the assumption to use the baseurl, rather than the apibaseurl which we pass in to the test-runs via the command-line.

test_that_carousel_works fails on production (https://github.com/mozilla/Addon-Tests/blob/master/tests/desktop/test_discovery_page.py#L90) as a result of this.

Like the API tests, we should instead use the apibaseurl, which on prod is https://services.addons.mozilla.org/

**Comment by justinpotts** [comment]
@stephendonner, It looks like running the test with the apibaseurl isn't working either. Am I missing something?

>$ py.test --baseurl=https://services.addons.mozilla.org --driver=firefox --credentials=/Users/admin/Documents/Development/Mozilla/credentials.yaml -k test_that_carousel_works

Returns:

>
INTERNALERROR> AssertionError: Base URL did not return status code 200 or 401. (URL: https://services.addons.mozilla.org, Response: 403)

**Comment by m8ttyB** [comment]
@stephendonner is it expected that https://services.addons.mozilla.org/ returns a 403?

**Comment by m8ttyB** [comment]
Just to be clear -- the expected GET would be https://services.addons.mozilla.org/en-US/firefox/discovery/pane/34.0.5/Darwin

**Comment by m8ttyB** [comment]
It appears that the API tests use `base_url` -- https://github.com/mozilla/Addon-Tests/blob/master/pages/desktop/addons_api.py#L22. I also don't see a `--apibaseurl` option in https://github.com/davehunt/pytest-mozwebqa/blob/master/pytest_mozwebqa/pytest_mozwebqa.py

I'll look through the Jenkins job to see if there is an example where https://services.addons.mozilla.org/ is used.

**Comment by m8ttyB** [comment]
Thanks @davehunt for pointing out https://github.com/mozilla/Addon-Tests/blob/master/conftest.py#L14 .. learn something new everyday :-)

**Comment by stephendonner** [comment]
The Add-ons Manager uses the services.addons.mozilla.org URL for security + other (perf, likely) reasons, rather than addons.mozilla.org.  @oremj + @jasonthomas - can you clarify, elaborate, when you get a chance?  Thanks!

**Comment by m8ttyB** [comment]
This was resolved by #747  -- closing.
