### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by flik** [mozilla/Addon-Tests#748]
I was testing this command and getting error
py.test --driver=firefox --credentials=./credentials.yaml

error:
py.test: error: no such option: --driver

**Comment by m8ttyB** [comment]
Hi @flik -- did you install the libraries in the `requirements.txt` file? https://github.com/mozilla/Addon-Tests/blob/master/requirements.txt

Try running or re-running `pip install -U -r requirements.txt`. The option `--driver` becomes available once the `pytest-mozwebqa` library is installed.

**Comment by flik** [comment]
yes. I have installed again and here are results:

gith@witz:~/Addon-Tests$ sudo pip install -U -r requirements.txt
[sudo] password for gith: 
Requirement already up-to-date: PyYAML==3.10 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: UnittestZero in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: certifi==0.0.8 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: chardet==2.1.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: execnet==1.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: oauthlib==0.5.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: py==1.4.15 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: pyasn1==0.1.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: pytest==2.3.5 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: pytest-mozwebqa in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: pytest-xdist==1.8 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already up-to-date: requests==2.4.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already up-to-date: rsa==3.1.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already up-to-date: selenium in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Obtaining browserid from git+https://github.com/mozilla/bidpom.git@master#egg=browserid (from -r requirements.txt (line 17))
  Updating ./src/browserid clone (to master)
Installing collected packages: browserid
  Running setup.py develop for browserid
    Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
    /usr/bin/python -E -c pass
    TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
    Creating /usr/local/lib/python2.7/dist-packages/browserid.egg-link (link to .)
    browserid 1.0 is already the active version in easy-install.pth
    Installed /home/gith/Addon-Tests/src/browserid
Successfully installed browserid-1.0
gith@witz:~/Addon-Tests$ py.test --driver=firefox --credentials=./credentials.yaml
Usage: py.test [options] [file_or_dir] [file_or_dir] [...]

py.test: error: no such option: --driver

**Comment by m8ttyB** [comment]
Very strange -- what output is returned when you run `pip freeze` from your development env?

**Comment by m8ttyB** [comment]
@flik -- if you're still experiencing problems, please join us in irc, #mozwebqa and we'll try to work through the problem in real-time and help get your development env working
