### ISSUE TITLE
Remove xfail - Relax the search filters for theme search to allow more results

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/Addon-Tests#755]
The version of Firefox that tests are run against sometimes have small subsets of search results that can produce false positives. This can be due to our test automation infrastructure using older versions of Firefox.

* Remove the xfail on `test_searching_for_addon_type_returns_results_of_correct_type()`.
* Update the appropriate Page Object with these filter options and have the test use them.
*  Relax the search filter to include results to `Any Firefox` and `All Systems` - https://github.com/mozilla/Addon-Tests/blob/master/tests/desktop/test_search.py#L228.

Example:
* URL before test update - causes test to fail - https://addons.allizom.org/en-US/firefox/search/?q=nasa&cat=2%2C0&appver=33.0&platform=windows
* URL after _fixing_ the test - https://addons.allizom.org/en-US/firefox/search/?q=nasa&cat=2%2C0&appver=any&platform=all

Click on these areas
![screenshot 2015-02-24 13 28 48](https://cloud.githubusercontent.com/assets/63193/6358736/1107cc98-bc2b-11e4-9cce-a8f835ab72da.png)

**Comment by m8ttyB** [comment]
Just wanted to capture notes from our irc discussion. `class FilterBase` appears to be the right entry point for which POM to update.

https://github.com/mozilla/Addon-Tests/blob/master/pages/desktop/regions/search_filter.py#L12

**Comment by m8ttyB** [comment]
@justinpotts do you have an eta for when you'll be able to work on this? Let me know if you need to put this task back into the pool for others to work on.

I'd like to see this resolved by the end of this week, Friday.

**Comment by justinpotts** [comment]
I'll go ahead and give it up.

**Comment by m8ttyB** [comment]
Cool beans .. thanks and no worries @justinpotts. /me throws this back into the issue pool https://d324imu86q1bqn.cloudfront.net/uploads/asset/attachment/2110801/ello-398d6e1e-cb10-4c62-a645-0fda59cbca4a.gif

**Comment by bobsilverberg** [comment]
I will take this.

**Comment by bobsilverberg** [comment]
Actually, I just noticed that when I assigned myself, that unassigned @m8ttyB. Did you want to work on this Matt? If so I'll leave it for you.

**Comment by m8ttyB** [comment]
I've got a pr that is close to done. Was waiting for a response to [Bug 1142302](https://bugzilla.mozilla.org/show_bug.cgi?id=1142302). I'll have a pr in today.

**Comment by m8ttyB** [comment]
pr #758 was merged .. bumping this to closed.
