### ISSUE TITLE
Intermittent failure with test_that_checks_the_desktop_version_link loading the wrong page

### ISSUE THREAD

**Issue by davehunt** [mozilla/Addon-Tests#763]
It appears that [test_that_checks_the_desktop_version_link](https://github.com/mozilla/Addon-Tests/blob/2bbc9c0598b1f3ed809457f6b5ecf58b08f245c7/tests/mobile/test_home.py#L25) sometimes fails because we end up on the 'most popular' addons page instead of the home page.

Before clicking the desktop link both a passing and failing test appear to be on the correct page of the mobile site:

![Mobile site](https://assets.saucelabs.com/jobs/a204cb2b86e44199bb3cc4218be6ae48/0001screenshot.png)

After [clicking the desktop link](https://github.com/mozilla/Addon-Tests/blob/2bbc9c0598b1f3ed809457f6b5ecf58b08f245c7/pages/mobile/base.py#L33) we are [expecting the home page](https://github.com/mozilla/Addon-Tests/blob/2bbc9c0598b1f3ed809457f6b5ecf58b08f245c7/pages/desktop/home.py#L52):

![Desktop home page](https://assets.saucelabs.com/jobs/a204cb2b86e44199bb3cc4218be6ae48/0002screenshot.png)

However we are sometimes getting the 'most popular' addons page from the desktop site.

![Desktop most popular page](https://assets.saucelabs.com/jobs/21725db0a73742cdbe22d1bad4f2db5e/0003screenshot.png)

We need to determine the cause and fix it. Perhaps there's a cookie or we're clicking the wrong element?

**Comment by davehunt** [comment]
I have been able to replicate this on my Samsung Galaxy S2 using the default browser (which is what we're using via Sauce Labs). It appears that I'm unable to load the desktop home page in the default browser at all, as I keep getting redirected to the most popular page. I am unable to replicate this issue in Firefox on my device, so it may be invalid. @krupa what are your thoughts?

**Comment by tarun1992** [comment]
I would like to take the issue.

**Comment by davehunt** [comment]
@tarun1992 this may be an a bug within the application under test as I'm able to replicate it manually. Let's see if we can find out from @krupa if we need to support the default browser on Android. For now, I'd suggest picking another issue.

**Comment by tarun1992** [comment]
I will pick another task @davehunt

**Comment by davehunt** [comment]
This has been passing for a while. Let's close and create a new issues if it comes back.
