### ISSUE TITLE
Update the test add-on used in https://github.com/mozilla/Addon-Tests/blob/master/tests/desktop/test_details_page.py#L128

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#769]
https://github.com/mozilla/Addon-Tests/blob/master/tests/desktop/test_details_page.py#L128 uses F1 by Mozilla Labs as the test add-on which was removed. We need to find a different test add-on

**Comment by davehunt** [comment]
Maybe [Restartless Addon with EULA](https://addons.mozilla.org/en-US/firefox/addon/restartless-addon-with-eula/) or [MemChaser](https://addons.mozilla.org/en-US/firefox/addon/memchaser/)?

**Comment by stephendonner** [comment]
Or https://addons.mozilla.org/en-US/firefox/addon/passwordprotect/ from @vaidik

**Comment by krupa** [comment]
All these options are valid.

**Comment by davehunt** [comment]
I think it may be better to use one we have direct control over, such as the Automation Development ones mentioned.

**Comment by stephendonner** [comment]
The test is test_other_addons_label_when_there_is_only_one_author, and qa-auto has 4 add-ons, which is why I suggested @vaidik's, as he only has one :-)

**Comment by davehunt** [comment]
The ones I linked only have one author. That author has multiple addons, but that shouldn't be an issue.

**Comment by stephendonner** [comment]
/me facepalms - yes, thanks.  I should know to stay out of these!

**Comment by davehunt** [comment]
Fixed by https://github.com/mozilla/Addon-Tests/commit/cedf348398f4cf92faaec58a1268fe24367a354d
