### ISSUE TITLE
Update  	test_that_searching_for_cool_returns_results_with_cool_in_their_name_description to account for tags

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#781]
test_that_searching_for_cool_returns_results_with_cool_in_their_name_description finds the add-on https://addons-dev.allizom.org/en-US/firefox/addon/smallringfx-darkblue/?src=search and fails because the search term "cool" is not in the description. However, the add-on is tagged with the keyword "cool" which is why the add-on is listed among the search results which is the correct behavior. Let us update the test to include keywords or check a specific add-on's description.

**Comment by davehunt** [comment]
@krupa can you clarify what you'd like this test to do? Currently it is searching for 'cool' and then checking that each result in the first page either has 'cool' in the name, or in the developer comments, or in the description. Are you saying you want to also check the keywords field? In my opinion these could be four separate tests, but that would likely require us to create addons with unique strings in each of those fields.

**Comment by krupa** [comment]
We can make them 4 separate tests with unique add-ons. Let me know if you need help creating the add-ons.

**Comment by davehunt** [comment]
I've probably asked this before, apologies if so, but can we create these through the API? It would make the tests much more reliable. If we go ahead and create them manually, do we need to do it for all environments?

**Comment by krupa** [comment]
There is no API we can do that currently. But, I can file an enhancement request to get it in place. Until that gets done, we should consider how we want to ensure coverage.

**Comment by davehunt** [comment]
Thanks @krupa, let's update this issue with more information when we have it. If this test is failing often then a short term fix could be to assert that the word 'cool' is in the name, description, developer notes, or keywords.

**Comment by davehunt** [comment]
We've decided this test is currently too vague, so let's remove it.
