### ISSUE TITLE
Update tests to accomodate for the locator change

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#787]
https://webqa-ci.mozilla.com/job/amo.dev/lastCompletedBuild/testReport/ is failing because of a locator change. We need to update the tests to see green again.

**Comment by bobsilverberg** [comment]
Here's a better link to the failing report: https://webqa-ci.mozilla.com/view/Buildmaster/job/amo.dev/364/HTML_Report/.

The above link can become stale.

I am working on a PR for this.
