### ISSUE TITLE
Fix test_reviews.TestReviews	test_that_new_review_is_saved failure

### ISSUE THREAD

**Issue by rbillings** [mozilla/Addon-Tests#790]
test_reviews.TestReviews test_that_new_review_is_saved began failing* after this commit:

https://github.com/mozilla/olympia/commit/a43d0c4c9431c8122a13c909ab512b6719d20496

*https://webqa-ci.mozilla.com/job/amo.dev.saucelabs/512/

Issue does not repro manually, and the id_body locator has not changed however re-running the build prompts further failures.

**Comment by davehunt** [comment]
This appears to be a locator change caused by https://github.com/mozilla/olympia/pull/720. I'll submit a PR with a fix.
