### ISSUE TITLE
Suggestion: rename repo name to be plural, "Addons-Tests"

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#799]
This has always nagged at me, and it's not really all that important, but the name of this repo really should be "Addons-Tests" rather than "Addon-Tests"

If that has an impact on history/workflow, and/or is too disruptive, mark as invalid :-)

**Comment by davehunt** [comment]
I would also like to make it lower case to match our other repositories, but I don't think it's worth the disruption. Also, I understand that in Q1 we'll be working on our automation for add-ons, which might include moving these tests into the same repository as the application code.

**Comment by stephendonner** [comment]
Yeah - given that we'll soon be moving this to https://github.com/mozilla/addons-server and that workflow (hopefully), I'm closing this out.  Not worth the effort in the interim, IMHO.
