### ISSUE TITLE
AMO is switching to FxA; tests need to be updated

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#800]
AMO is switching to FxA; tests which require logging in need to be updated

Note that dev is already pointing to FxA.

**Comment by bobsilverberg** [comment]
Great news, thanks @krupa!

Do we have a timeline as to when this is going to happen? On dev, stage and prod?

**Comment by krupa** [comment]
It is already on dev.

Stage and prod probably won't happen until q1 of next year.

**Comment by bobsilverberg** [comment]
As we already did this switch for Marketplace, I would suggest that whoever takes this task should check the code used there [1]. Specifically of interest are `conftest.py` [2] and `base.py` in `desktop/consumer_pages`.

We will also need to maintain the code for Persona login for stage and prod, but allow tests running on dev to use FxA.

[1] https://github.com/mozilla/marketplace-tests
[2] https://github.com/mozilla/marketplace-tests/blob/master/conftest.py
[3] https://github.com/mozilla/marketplace-tests/blob/master/pages/desktop/consumer_pages/base.py#L52

**Comment by MonicaG** [comment]
I would like to try this, but I'm wondering what the timeline is like?  Do you need this in a matter of days? weeks?  

I'm just poking around at the code trying to get a handle on what the code does and what changes are needed.

**Comment by stephendonner** [comment]
Hi there, @MonicaG - and thanks, so much (!) for this (and other, pull[s]); the latest build status can always be seen on https://webqa-ci.mozilla.com/view/AMO/ - we welcome and encourage you (and others!) to help us keep these builds green and growing!  Thx in advance!

**Comment by bobsilverberg** [comment]
@MonicaG Ideally it would be completed in days, rather than weeks, as this is causing a number of our tests to fail. If you think you'll have time to devote to it then we'd love to have you work on it, but if not then perhaps choose a lower priority issue.  Thanks for the interest!

**Comment by MonicaG** [comment]
@bobsilverberg I'll look for a lower priority issue.  I don't think I'll have the time to get this done in the next few days.

**Comment by krupa** [comment]
@davehunt can we close this?

**Comment by davehunt** [comment]
Yes, thanks @krupa!
