### ISSUE TITLE
Test for signing API 

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#801]
We now have signing API which developers can use to get their add-ons signed. We should test that an add-on can be signed using that API and then can be successfully installed using Firefox.

**Comment by stephendonner** [comment]
http://addons-server.readthedocs.io/en/latest/topics/api/signing.html, I think?

**Comment by stephendonner** [comment]
@stupchiy are you interested in this one?

**Comment by stupchiy** [comment]
yup @stephendonner ;-)

**Comment by stupchiy** [comment]
@krupa is that should be API level tests only or also reflected somehow in UI?
And what credentials can I use ? @stephendonner can I use the same you gave me before for Addon-Tests?

**Comment by stephendonner** [comment]
@stupchiy as long as they still work, sure :-)

**Comment by stupchiy** [comment]
@krupa, @stephendonner need more info on that to continue. 

- In the doc there are already v3 of API described, in Addon-Tests used 1.5, should it be switched to latest?
- Described Signin process, contains instructions to upload the addon. Is that could be done with already existing addon, or should we upload some "test-addon"?
- Could you also elaborate more on - test that signed addon "can be successfully installed using Firefox" ? How it could be done, is there already some functionality exist?

Regards

**Comment by davehunt** [comment]
We're retiring this repository in the next few weeks. I suspect this issue is outdated by now, and most likely covered elsewhere.
