### ISSUE TITLE
Intermittent failure in test_searching_for_addon_type_returns_results_of_correct_type[Complete Themes-nasa-Complete Themes]

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#803]
We need to investigate why test_searching_for_addon_type_returns_results_of_correct_type[Complete Themes-nasa-Complete Themes] is an intermittent failure on both amo.stage.saucelabs and amo.prod.* (it's likely also failing on dev, but due to the restyling changes landed on master/dev in https://github.com/mozilla/olympia/pull/1078 it's hard to tell.

Some early investigation:
1. The URL we print on failure is https://addons.mozilla.org/en-US/firefox/search/?atype=2&q=nasa&platform=windows&appver=42.0
2. Here's a video of a passing run via Sauce Labs: https://saucelabs.com/jobs/ba9123e8844e46e3816d1d905cbdf69f from https://webqa-ci.mozilla.com/view/AMO/job/amo.prod.saucelabs/819/
3. Not sure if this is related, but if you just load https://addons.mozilla.org/en-US/firefox/search/?atype=2&q=nasa&platform=windows&appver=42.0 and try to toggle the "Category" filter criteria, it doesn't expand.  It *does* for me, if I load https://addons.mozilla.org/en-US/firefox/search/?q=nasa&platform=windows&appver=42.0 instead (which omits the ?atype=2 param and its value - might need to turn this into a bug).

**Comment by stephendonner** [comment]
Attaching this annotated screenshot from the "inability to toggle" failure-case from 3), in case it's useful for filing a bug later.
<img width="1792" alt="screen shot 2016-01-06 at 7 31 17 pm" src="https://cloud.githubusercontent.com/assets/387249/12161941/7687b91a-b4b0-11e5-8108-005cf4dace92.png">

**Comment by davehunt** [comment]
It looks like we're waiting for the update spinner to be hidden, but getting a stale element exception. It's quite possible that the element is removed from the DOM after being hidden, which could cause this intermittent. I'll work on a patch to make this more robust.

**Comment by stephendonner** [comment]
The issue I noted in 3) has been logged by @davehunt as https://github.com/mozilla/olympia/issues/1247

**Comment by davehunt** [comment]
This has been passing for a while now. The test was refactored, and no longer fails due to mozilla/addons-server#1247. Let's remove the xfail. @stephendonner or @stupchiy want to take this?

**Comment by davehunt** [comment]
Closed by #854
