### ISSUE TITLE
Update mobile suite to work with latest stable version of Appium

### ISSUE THREAD

**Issue by davehunt** [mozilla/Addon-Tests#806]
Our mobile suite is currently running with the following capabilities in Sauce Labs:

```
browserName: browser
platformVersion: 4.4
platformName: android
deviceName: Android
appiumVersion: 1.3.7
```

We should update the suite to work with the stable latest version of Appium, which may also mean updating the platform.

**Comment by rbillings** [comment]
Stable release version numbers can be found here: https://github.com/appium/appium/releases

**Comment by rbillings** [comment]
@davehunt - how would someone know if the platform needs to be updated, and to which version?

**Comment by davehunt** [comment]
We are not able to update to Android 5.1 due to https://github.com/appium/appium/issues/6330. I think we can close this, and track that issue instead.
