### ISSUE TITLE
Move Add-on Tests to the dev repo

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#815]
We want to be running our Selenium tests upon every PR. Towards that goal, let us move our existing tests to the dev repo.

**Comment by bebef1987** [comment]
Do you want to fully move this to the dev repo or just add it as an submodule?

**Comment by davehunt** [comment]
Unlikely to be a submodule, this is going to be discussed on dev-addons soon.

Cheers,
Dave Hunt

**Comment by davehunt** [comment]
I've kicked off a discussion about this:
https://mail.mozilla.org/pipermail/dev-addons/2016-March/000459.html

**Comment by davehunt** [comment]
I've opened a pull request for the initial tests here: https://github.com/mozilla/addons-server/pull/2722

**Comment by davehunt** [comment]
This is continuing thanks to @jrbenny35's work, and we'll be retiring this repository in the next few weeks.
