### ISSUE TITLE
Update the URL for AMO disco pane tests

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#817]
Currently we are using https://addons.allizom.org/en-US/firefox/discovery/pane/47.0a1/Darwin/normal in our tests. We should be using https://addons-services.allizom.org/en-US/firefox/discovery/pane/47.0a1/Darwin/normal instead.

Thanks!

**Comment by davehunt** [comment]
This is already configurable using the `--servicesbaseurl` command line option. Is anything else needed here? Is this something that's changed recently @krupa?

**Comment by davehunt** [comment]
Also, is https://addons-services.allizom.org staging or dev? Is there both a staging and dev environment available for testing?

**Comment by krupa** [comment]
Looks like the endpoint changed recently (and again)

New endpoint for dev is  https://services.addons-dev.allizom.org and stage will be updated after tomorrow's push

Sorry about the churn.

**Comment by davehunt** [comment]
I've changed the dev jobs in Jenkins to include `--servicesbaseurl https://services.addons-dev.allizom.org`, which appears to have resolved the outstanding failures. I'll leave this open to remind us to update the staging jobs once we have a working URL.

**Comment by krupa** [comment]
Stage has been updated and once we update that link all the related tests will start passing.

**Comment by davehunt** [comment]
Thanks @krupa, this is now fixed!
