### ISSUE TITLE
test_that_new_review_is_saved fails on dev/stage due to timestamp difference

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#821]
This will soon hopefully "just go away," (in a couple hours?) but right now we've got failures in both amo.dev.saucelabs and amo.stage.saucelabs due to timestamp differences, which affects test_that_new_review_is_saved:

Staging: https://webqa-ci.mozilla.com/view/AMO/job/amo.stage.saucelabs/795/testReport/tests.desktop.test_reviews/TestReviews/test_that_new_review_is_saved/
Dev: https://webqa-ci.mozilla.com/view/AMO/job/amo.dev.saucelabs/806/testReport/tests.desktop.test_reviews/TestReviews/test_that_new_review_is_saved/

The failures look like this (off-by-day error):

22:30:43 =================================== FAILURES ===================================
22:30:43 __________________ TestReviews.test_that_new_review_is_saved ___________________
22:30:43 [gw14] linux2 -- Python 2.7.9 /var/lib/jenkins/jobs/amo.dev.saucelabs/workspace/.venv/bin/python2.7
22:30:43 tests/desktop/test_reviews.py:77: in test_that_new_review_is_saved
22:30:43     assert expected_date == review.date, 'Date of review does not match the expected value.'
22:30:43 E   AssertionError: Date of review does not match the expected value.
22:30:43 E   assert 'February 29, 2016' == 'March 1, 2016'
22:30:43 E     - February 29, 2016
22:30:43 E     + March 1, 2016

**Comment by stephendonner** [comment]
This also happened on amo.dev (non Sauce Labs):

https://webqa-ci.mozilla.com/view/AMO/job/amo.dev/604/testReport/junit/tests.desktop.test_reviews/TestReviews/test_that_new_review_is_saved/

**Comment by stephendonner** [comment]
6:05 AM <jason> stephend|afk: all our services should be running on UTC
6:06 AM <jason> the error in https://webqa-ci.mozilla.com/view/AMO/job/amo.dev/604/testReport/junit/tests.desktop.test_reviews/TestReviews/test_that_new_review_is_saved/
6:06 AM <jason> E     - March 7, 2016 E     + March 8, 2016
6:06 AM <jason> makes me wonder if there is a time zone difference here
6:06 AM <jason> since the output is t https://stable.dev.lcip.org/auth/ on 2016-03-08 00:04:53.170626
6:08 AM <jason> yeah, that job ran at  (Mar 7, 2016 3:58:49 PM) 
6:08 AM <jason> so maybe adjust the tests to use UTC instead?

**Comment by stephendonner** [comment]
https://github.com/mozilla/Addon-Tests/blob/master/tests/desktop/test_reviews.py#L63 is currently:

 date = datetime.now(timezone('US/Pacific')).strftime("%B %d, %Y")

**Comment by davehunt** [comment]
Taking this to restore coverage. Sorry @bebef1987

**Comment by bebef1987** [comment]
:(( sorry for taking that much time with this
