### ISSUE TITLE
Fix test : test_navigation_buttons_for_image_viewer

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#841]
test_navigation_buttons_for_image_viewer  is currently failing due to a timeout.

_next_locator = (By.CSS_SELECTOR, 'section.previews div.carousel > a.next')
 _prev_locator = (By.CSS_SELECTOR, 'section.previews div.carousel > a.prev')
look valid to me. I'm unsure what is causing the Timeout.

**Comment by davehunt** [comment]
I'm going to close this, but we can reopen if we see it again.
