### ISSUE TITLE
fix test: test_that_checks_the_up_and_coming_extensions_island 

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#843]
test_that_checks_the_up_and_coming_extensions_island is failing because for some reason the test is loading the devhub landing page. My guess that we are not waiting sufficiently long enough for the page to load and the wrong element is being clicked.

**Comment by davehunt** [comment]
It looks like the add-on islands have changed, and no longer have a pager. For some very strange reason the test is clicking the page footer before attempting to click the next page in the island (which would fail itself), and this is actually clicking the Developer Hub link in the footer. I'm going to clean up the test and the page object to remove the reference to pagination in the island.
