### ISSUE TITLE
Test to check for unlisted add-on submission 

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#851]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/developers/addon/submit/2
2. Select the checkbox -  Do not list my add-on on this site
3. Upload your add-on
4. After successful validation, click Continue
5. Complete the submission process
6. Download the signed copy of the add-on file
7. Check that the file is actually signed by checking for the META-INF folder when the file is unzipped.

**Comment by davehunt** [comment]
@krupa please check to see if the labels I've applied are appropriate

**Comment by davehunt** [comment]
We're retiring this repository in the next few weeks. This could be considered as a potential test case for the new suite, @jrbenny35.
