### ISSUE TITLE
Intermittent failure: tests.desktop.test_paypal.TestPaypal.test_that_user_can_contribute_to_an_addon

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#853]
Looks like the test tests.desktop.test_paypal.TestPaypal.test_that_user_can_contribute_to_an_addon is flaky and particularly so on our saucelabs instance. It might be the particular window size saucelabs uses, but the test definitely needs an overhaul in terms of reliability.

**Comment by stephendonner** [comment]
According to https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-SpecifyingtheScreenResolution "Default screen resolution for Sauce tests when not specified is 1024x768." which is the same resolution our own Windows 7 virtual machines are currently set to.

@stupchiy had a point - I wonder if part of this could be the higher concurrency in Sauce, hitting PayPal "hard" at the same time?  With Sauce Labs jobs, we set -n 15, but with our in-house Grid jobs on Windows (amo.dev) we set -n 4.  Also, looking at our configs, we only have one PayPal test account, which might support this theory (but I've yet to prove or even try this - I'll take a look tomorrow, if nobody beats me to it.)

**Comment by davehunt** [comment]
We don't hit any harder with Sauce Labs. The concurrency is the number of tests that run in parallel. There are no additional tests running that would cause any significant increased impact on Paypal.

**Comment by stupchiy** [comment]
@davehunt what about jobs running in parallel - `amo.prod`, `amo.dev.saucelabs`, `amo.dev`, etc. ? Is that a case? I was pointing to the jenkins jobs specifically, since as @stephendonner mentioned paypal account for all of them the same.

**Comment by davehunt** [comment]
That wouldn't make Sauce Labs any more likely to timeout than Grid though, as they're running at the same time. I wouldn't focus on why this is currently less stable on Sauce, as we have also seen these fail on Grid. We should focus on making the tests more stable, explicitly marking them as flaky with a maximum number of reruns, or deleting them if they're not essential.

**Comment by davehunt** [comment]
We're retiring this repository in the next few weeks, and I believe the PayPal functionality has been removed.
