### ISSUE TITLE
Load discopane from Tools -> Add-ons

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#862]
## set up instructions:
https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing

## steps to test:
1. On a new profile, launch Firefox 48 or higher
2. Tools -> Add-ons

## things to check:
1. On a new profile, all the buttons are grey/off
2. There is a section 'Personalize Your Firefox' and the video can be launched. When the video is launched, there is a 'close video' 
3. On hover, the themes get previewed
4. There is a button 'See more add-ons' which links to addons.mozilla.org

**Comment by justinpotts** [comment]
Closed in https://github.com/mozilla/addons-frontend/pull/788
