### ISSUE TITLE
Install an add-on from discopane

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#863]
## set up instructions:

https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing
## steps to test:
1. On a new profile, launch Firefox 48 or higher
2. Tools -> Add-ons
3. Install an add-on by clicking on the switch
## things to check:
1. The install button is green with a √ in it
2. There is an UiTour which happens after the add-on is installed (still an open bug)
3. The installed add-on is listed in Extensions tab

**Comment by justinpotts** [comment]
Fixed with pull #868

**Comment by davehunt** [comment]
I think you meant to mark #820 as fixed, this is still open.

**Comment by davehunt** [comment]
We're retiring this repository in the next few weeks. @jrbenny35: I believe this would still be a useful test, perhaps for the suite in https://github.com/mozilla/addons-frontend/tree/master/tests/ui
