### ISSUE TITLE
Fix failing test: test_user_can_login_and_logout

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#877]
Looks like tests/desktop/test_users_account.py::TestAccounts::()::test_user_can_login_and_logout is failing with  NoSuchElementException: Message: Unable to locate element: {"method":"id","selector":"id_username"}

This needs to be fixed.

**Comment by krupa** [comment]
I think test_web_extension_submission is also failing for the same element.

**Comment by davehunt** [comment]
This was fixed by #878
