### ISSUE TITLE
Switch to Tox

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#880]
bidpom and fxapom have already switched, and this is now being tracked in our Baseline: https://wiki.mozilla.org/TestEngineering/Web/Automation/Baseline

Let's switch over to Tox: https://tox.readthedocs.io/en/latest/

**Comment by davehunt** [comment]
This was done in https://github.com/mozilla/Addon-Tests/commit/137649e7833cac52287e71e5989f18af361e2159
