### ISSUE TITLE
Hook up/restore higher test-execution concurrency (n=) using PYTEST_PROCESSES

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#892]
Our build times have increased greatly (for at least amo.prod, from ~2-3 minutes to 11 minutes, as a prime example) since https://github.com/mozilla/Addon-Tests/pull/888.

In chatting with @davehunt we should likely use PYTEST_PROCESSES, but fall back to AUTO (which we're currently using, and is based on the # of cores) if that's unset, for safety.

**Comment by davehunt** [comment]
Fixed by https://github.com/mozilla/Addon-Tests/commit/425271a4b84dbccbdbb16996bacc689dfdbdf76f
