### ISSUE TITLE
Enable pyup.io for taking care of dependencies

### ISSUE THREAD

**Issue by davehunt** [mozilla/Addon-Tests#902]
We want to enable [pyup.io](https://pyup.io/) for our projects to take care of automating the updates to our dependencies. Here's what's needed:

- [x] Move dependencies out of `tox.ini` and into requirements files. See https://github.com/mozilla/PyPOM/commit/ad21988d0364843808c07f3aaa656c6c16b971b2 for an example of this.
- [x] Add repository to pyup.io (@davehunt can take care of this once the above is merged).
- [x] Add pyup.io badges for updates and python 3 readyness. See https://github.com/mozilla/PyPOM/commit/931c41b964f1c9950983c078d0583ef708ac8af9 for an example of this.
- [x] Remove requires.io badge from README.
- [x] Remove repository from [requires.io](https://requires.io/) (@davehunt can take care of this once pyup.io is working)

**Comment by davehunt** [comment]
@stephendonner I've enabled the project in pyup.io and the initial update is in #905. Let me know if you need anything else from me.

**Comment by stephendonner** [comment]
@davehunt thanks; just the remaining two items: 1) removing repo from requires.io + 2) adding pyup.io badges, if you don't mind!

**Comment by stephendonner** [comment]
(Actually, I can probably take care of badges?)

https://pyup.io/repos/github/mozilla/addon-tests/shield.svg

I'll get a pull going for that.

**Comment by davehunt** [comment]
I don't seem to be able to deactivate requires.io at this time. I'll try again later.

**Comment by davehunt** [comment]
Okay, it's been deactivated now.

**Comment by stephendonner** [comment]
All done; closing!
