### ISSUE TITLE
Fix failing/hard-coded ("5") Firebug-rating test; use, instead addons_api to get its env-specific rating

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#916]
We've hard-coded "5" for the Firebug add-on's rating in https://github.com/mozilla/Addon-Tests/blob/59dfccceedd11ba428bf2e154e8e7ba6f4d9757e/tests/desktop/test_details_page_against_xml.py#L77

Instead, we should probably use https://github.com/mozilla/Addon-Tests/blob/59dfccceedd11ba428bf2e154e8e7ba6f4d9757e/pages/desktop/addons_api.py#L133 to get its rating via XML, and compare to the add-on page.

**Comment by davehunt** [comment]
This is a pretty useless test. It's in a module that suggests we should be checking against the XML returned from the API. If this is indeed a useful test then we should fix it. I suspect that moving the tests to addons-server would allow us to create an addon with a specific rating and ensure that the correct rating is displayed. There may already be such a test for the XML, so we wouldn't need to do a comparison.

@jrbenny35 could you discuss this with @krupa and either remove or fix this test base on the outcome of that discussion? I can't assign this to you as you're not yet a member of the mozilla organisation on GitHub. I believe an invitation has been sent.

**Comment by jrbenny35** [comment]
Will do
