### ISSUE TITLE
Switch to Declarative Pipeline and submit to activeData?

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#924]
We should probably hook up both Declarative Pipeline, as well as activeData (can be separate Issues/PRs).

@jrbenny35 is this on your radar?  Or @davehunt?  I'd be happy to give it a crack, but would likely need help with straightening out py27/desktop/mobile in tox.ini, and elsewhere...

**Comment by davehunt** [comment]
Yeah, the difference with this suite is that we're running parallel build steps. Should be possible in declarative, though. Feel free to take this, or I may get to it in time.

**Comment by stephendonner** [comment]
Gonna punt for now - fair game!
