### ISSUE TITLE
Fix test_web_extension_submission failure, by way of axl dependency

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#947]
https://github.com/justinpotts/axl/blob/e547ff573df237a4715a1510f4c2784596225b8f/axl/axl.py#L56 using @mozilla.org as the suffix of the extension's unique ID is why tests/desktop/test_extensions.py::TestExtensions::test_web_extension_submission has been failing:

'You cannot submit an add-on with a guid ending "@mozilla.org"'

![screenshot](https://cloud.githubusercontent.com/assets/387249/26436778/e6615a2a-40cd-11e7-8e10-9ec6c555d6b3.png)

See screenshot w/error.

**Comment by davehunt** [comment]
We're retiring this repository in the next few weeks, and the tests have relocated to https://github.com/mozilla/addons-server/tree/master/tests/ui.
