### ISSUE TITLE
Investigate why tests and slave node on Jenkins dev crash/time out

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Addon-Tests#971]
This doesn't really seem to be an issue with the tests themselves, but filing here so I remember to follow-up.

Need to investigate/ping Ops or other folks to see why our slave node on Jenkins dev crashes on AMO tests (might just be due to timeout/long-running tests killing the process?)

https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/amo.adhoc/80/consoleFull

/cc @davehunt

**Comment by davehunt** [comment]
This is because we have a timeout defined in the pipeline of 1 hour. The recent issue where only one process is being used is causing the tests to take considerably longer, and therefore causing timeouts.

**Comment by davehunt** [comment]
I believe we haven't seen this since moving to the new Jenkins instance with more processes available.
